################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c 

OBJS += \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.o \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.o \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.o 

C_DEPS += \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.d \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.d \
./MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.d 


# Each subdirectory must supply rules for building sources it contributes
MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.o: ../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072CBTx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -DSTM32 -DDEBUG -DSTM32L0 -c -I../Inc -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/QuarkTS/include" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/CMSIS" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MCU" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/WSQ" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/Target" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Drivers/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Debounce" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/SigFox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/Sigfox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/AT_cli" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Bsp" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Temp_Hum" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_core.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.o: ../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072CBTx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -DSTM32 -DDEBUG -DSTM32L0 -c -I../Inc -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/QuarkTS/include" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/CMSIS" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MCU" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/WSQ" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/Target" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Drivers/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Debounce" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/SigFox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/Sigfox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/AT_cli" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Bsp" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Temp_Hum" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.o: ../MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32L072CBTx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -DSTM32 -DDEBUG -DSTM32L0 -c -I../Inc -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/QuarkTS/include" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/CMSIS" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MCU" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/WSQ" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/MIddleware/USB_DEVICE/Target" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Drivers/Inc" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Debounce" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/SigFox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/Sigfox" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Services/AT_cli" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Bsp" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/App" -I"C:/Users/Julian/Desktop/wifi_git_2021/PRJ_IBUTTON_WSQ/FW/Ejemplo_QuarkTS/Source/Drivers/Temp_Hum" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"MIddleware/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

